var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};
$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var h=a[e];if(!(h in c))return;c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var h=a.split(".");a=1===h.length;e=h[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var n=0;n<h.length-1;n++){var p=h[n];if(!(p in e))return;e=e[p]}h=h[h.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[h]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[h]&&($jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(h):
$jscomp.POLYFILL_PREFIX+h),$jscomp.defineProperty(e,$jscomp.propertyToPolyfillSymbol[h],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),e=c.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(e.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var h=e.value}catch(n){return this.context_.yieldAllIterator_=null,this.context_.throw_(n),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(e){return a.next(e)}function c(e){return a["throw"](e)}return new Promise(function(e,h){function n(p){p.done?e(p.value):Promise.resolve(p.value).then(b,c).then(n,h)}n(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
function getFP(){var a,b,c,e,h,n,p;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:a={originHost:document.location.host,originUrl:document.location.href,referrer:document.referrer||"",isMobile:function(d){var f=/android|ipad|playbook|silk/i;d="";d||"undefined"===typeof navigator||(d=navigator.userAgent);d&&d.headers&&"string"===typeof d.headers["user-agent"]&&(d=d.headers["user-agent"]);if("string"!==typeof d)return!1;f=/(android|bb\d+|meego).+mobile|armv7l|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series[46]0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(d)||
f.test(d);!f&&navigator&&1<navigator.maxTouchPoints&&-1!==d.indexOf("Macintosh")&&-1!==d.indexOf("Safari")&&(f=!0);return f},"document.body.clientWidth":document.body.clientWidth,"document.body.clientHeight":document.body.clientHeight,"screen.width":screen.width,"screen.height":screen.height,"screen.availWidth":screen.availWidth,"screen.availHeight":screen.availHeight,"screen.colorDepth":screen.colorDepth,"screen.pixelDepth":screen.pixelDepth,"window.innerHeight":window.innerHeight,"window.outerHeight":window.outerHeight,
"window.outerWidth":window.outerWidth,"window.innerWidth":window.innerWidth,"window.screenX":window.screenX,"window.pageXOffset":window.pageXOffset,"window.pageYOffset":window.pageYOffset,"window.devicePixelRatio":window.devicePixelRatio,"navigator.userAgent":navigator.userAgent,"navigator.maxTouchPoints":navigator.maxTouchPoints||0,"navigator.msMaxTouchPoints":navigator.msMaxTouchPoints||0,"navigator.platform":navigator.platform||"unknown","navigator.languages":navigator.languages||"unknown","navigator.plugins":function(d){d=
[];for(var f={},g=0;g<navigator.plugins.length;f={$jscomp$loop$prop$mimeTypes$2:f.$jscomp$loop$prop$mimeTypes$2,$jscomp$loop$prop$plugin$3:f.$jscomp$loop$prop$plugin$3},g++){f.$jscomp$loop$prop$plugin$3=navigator.plugins[g];var m=[f.$jscomp$loop$prop$plugin$3.name,f.$jscomp$loop$prop$plugin$3.description,f.$jscomp$loop$prop$plugin$3.filename,f.$jscomp$loop$prop$plugin$3.version].join("::");f.$jscomp$loop$prop$mimeTypes$2=[];Object.keys(f.$jscomp$loop$prop$plugin$3).forEach(function(k){return function(q){k.$jscomp$loop$prop$mimeTypes$2.push([k.$jscomp$loop$prop$plugin$3[q].type,
k.$jscomp$loop$prop$plugin$3[q].suffixes,k.$jscomp$loop$prop$plugin$3[q].description].join("~"))}}(f));f.$jscomp$loop$prop$mimeTypes$2=f.$jscomp$loop$prop$mimeTypes$2.join(",");d.push(m+"__"+f.$jscomp$loop$prop$mimeTypes$2)}return d},"navigator.mimeTypes":function(d){d=[];for(var f=0;f<navigator.mimeTypes.length;f++){var g=navigator.mimeTypes[f];d.push([g.description,g.type,g.suffixes].join("~~"))}return d},touchEvent:function(d){d=!1;try{document.createEvent("TouchEvent"),d=!0}catch(f){}return{touchEvent:d,
touchStart:"ontouchstart"in window}},videoCard:function(d){try{var f=document.createElement("canvas"),g=f.getContext("webgl")||f.getContext("experimental-webgl");if(0<=g.getSupportedExtensions().indexOf("WEBGL_debug_renderer_info")){var m=g.getParameter(g.getExtension("WEBGL_debug_renderer_info").UNMASKED_VENDOR_WEBGL);var k=g.getParameter(g.getExtension("WEBGL_debug_renderer_info").UNMASKED_RENDERER_WEBGL)}else k=m="Not supported";return{webGLVendor:m,webGLRenderer:k}}catch(q){return null}},multimediaDevices:function(d){return new Promise(function(f){var g=
{audiooutput:0,audioinput:0,videoinput:0};navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&"bound reportBlock"!==navigator.mediaDevices.enumerateDevices.name?navigator.mediaDevices.enumerateDevices().then(function(m){if("undefined"!==typeof m){for(var k,q=0;q<m.length;q++)k=[m[q].kind],g[k]+=1;f({devices:m,speakers:g.audiooutput,micros:g.audioinput,webcams:g.videoinput})}else f({devices:[],speakers:0,micros:0,webcams:0})}):navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&
"bound reportBlock"===navigator.mediaDevices.enumerateDevices.name?f({devicesBlockedByBrave:!0}):f({speakers:0,micros:0,webcams:0})})},productSub:navigator.productSub,etsl:eval.toString().length,accelerometerUsed:function(d){return new Promise(function(f){window.ondevicemotion=function(g){if(null!==g.accelerationIncludingGravity.x)return f(!0)};setTimeout(function(){return f(!1)},300)})},screenMediaQuery:window.matchMedia("(min-width: "+(window.innerWidth-1)+"px)").matches,hasChrome:!!window.chrome,
iframeChrome:function(d){d=document.createElement("iframe");d.srcdoc="blank page";document.body.appendChild(d);var f=typeof d.contentWindow.chrome;d.remove();return f},battery:"getBattery"in window.navigator,deviceMemory:navigator.deviceMemory||0,tpCanvas:function(d){return new Promise(function(f){try{var g=new Image,m=document.createElement("canvas").getContext("2d");g.onload=function(k){m.drawImage(g,0,0);f(m.getImageData(0,0,1,1).data)};g.onerror=function(k){f("error")};g.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVQYV2NgAAIAAAUAAarVyFEAAAAASUVORK5CYII="}catch(k){f("error")}})},
sequentum:window.external&&window.external.toString&&-1<window.external.toString().indexOf("Sequentum"),audioCodecs:function(d){d=document.createElement("audio");return d.canPlayType?{ogg:d.canPlayType('audio/ogg; codecs="vorbis"'),mp3:d.canPlayType("audio/mpeg;"),wav:d.canPlayType('audio/wav; codecs="1"'),m4a:d.canPlayType("audio/x-m4a;"),aac:d.canPlayType("audio/aac;")}:{ogg:"unknown",mp3:"unknown",wav:"unknown",m4a:"unknown",aac:"unknown"}},videoCodecs:function(d){d=document.createElement("video");
return d.canPlayType?{ogg:d.canPlayType('video/ogg; codecs="theora"'),h264:d.canPlayType('video/mp4; codecs="avc1.42E01E"'),webm:d.canPlayType('video/webm; codecs="vp8, vorbis"')}:{ogg:"unknown",h264:"unknown",webm:"unknown"}}},b={},e=l.forIn(a);case 2:if(null==(c=e.getNext())){l.jumpTo(4);break}if("function"!==typeof a[c]){b[c]=a[c];l.jumpTo(5);break}b[c]=a[c]();if(!("object"===typeof b[c]&&"then"in b[c])){l.jumpTo(5);break}l.setCatchFinallyBlocks(7);h=b;n=c;return l.yield(b[c],9);case 9:h[n]=l.yieldResult;
l.leaveTryBlock(5);break;case 7:p=l.enterCatchBlock(),b[c]=p.message;case 5:if("object"===typeof b[c]||Array.isArray(b[c]))b[c]=JSON.stringify(b[c]);b[c]||0===b[c]||"boolean"===typeof b[c]||(b[c]="");l.jumpTo(2);break;case 4:return l["return"](b)}})}serialize=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")};
window.onload=function(a){var b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return e.yield(getFP(),2);b=e.yieldResult;c=new XMLHttpRequest;c.open("GET","https://script.google.com/macros/s/AKfycbyV4yi5qKBv7cnxs3ZZQgSI78cNnEOeWCDmDje35HBQyWDVlyOcPUvG-7NEz-RzDSDa3w/exec?"+serialize(b),!0);c.send();e.jumpToEnd()})};var imported=document.createElement("script");imported.src="https://www.googletagmanager.com/gtag/js?id=UA-196338574-1";document.head.appendChild(imported);
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date);gtag("config","UA-196338574-1");
